services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  python-app:
    build:
      context: ..
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"

volumes:
  postgres-data:
